### ISSUE TITLE
cannot run test on IE

### ISSUE THREAD

**Issue by filiprichtarik** [golemhq/golem#113] opened 2018-07-12 13:16 UTC
golem 0.5.0
python 3.6.5

when trying to run tests on IE, it fails on   File "c:\python365\lib\site-packages\golem\browser.py", line 57, in _find_webelement
    remaining_time = remaining_time - (time.time() - start_time)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
  
Full Trace>

File "c:\python365\lib\site-packages\golem\test_runner\test_runner.py", line 117, in run_test
    test_module.setup(execution.data)
  File "C:\Jenkins\workspace\golem_internet_explorer\projects\predict_automation\tests\advisor_student_list\clear_filters.py", line 9, in setup
    login.login_as_role('advisor', data)
  File "C:\Jenkins\workspace\golem_internet_explorer\projects\predict_automation\pages\login.py", line 11, in login_as_role
    wait_for_element_visible(privacy_agree_button)
  File "c:\python365\lib\site-packages\golem\actions.py", line 897, in wait_for_element_visible
    webelement = browser.get_browser().find(element)
  File "c:\python365\lib\site-packages\golem\browser.py", line 130, in _find
    element_name, timeout)
  File "c:\python365\lib\site-packages\golem\browser.py", line 57, in _find_webelement
    remaining_time = remaining_time - (time.time() - start_time)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

**Comment by lucianopuccio** [comment] 2018-11-14 05:30
Is this still happening? I can't reproduce in 0.6.1

**Comment by luciano-renzi** [comment] 2018-12-05 06:08
Closing, reopen if error persists

**Closed by luciano-renzi** 2018-12-05 06:08 UTC
